# Generated by Django 5.1.7 on 2025-03-12 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='student',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='message',
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
